import "./globals.css";
import "aos/dist/aos.css";
import AOSInit from "@/components/AOSInit";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <AOSInit />
        {children}

        <Footer />
      </body>
    </html>
  );
}
