export const transcript1 = [
  { time: 3, speaker: "Owner", text: "Hello?" },
  { time: 4, speaker: "Amy", text: "Hi, am I speaking to Ian?" },
  { time: 6, speaker: "Owner", text: "Yes, how can I help you?" },
  {
    time: 8,
    speaker: "Amy",
    text: "Hi, Ian. This is Amy. I was calling, recording the Property when it 1435 Burlingen. Wanted to see if you were interested in selling.",
  },
  { time: 18, speaker: "Owner", text: "No, I'm not." },
  {
    time: 20,
    speaker: "Amy",
    text: "And do you have any other properties you consider selling?",
  },
  { time: 25, speaker: "Owner", text: "Maybe." },
  { time: 28, speaker: "Amy", text: "Which state?" },
  { time: 31, speaker: "Owner", text: "Maybe one other." },
  { time: 36, speaker: "Amy", text: "It's in Michigan as well?" },
  { time: 39, speaker: "Owner", text: "Yes." },
  {
    time: 40,
    speaker: "Amy",
    text: "Okay, what's the address? Sorry, what did you say? I didn't catch that.",
  },
  { time: 47, speaker: "Owner", text: "Where are you located?" },
  { time: 49, speaker: "Amy", text: "Oh, we're in Michigan." },
  {
    time: 51,
    speaker: "Owner",
    text: "Okay, a second. 4890 Loadwick. That's around the corner from Gross Point.",
  },
  {
    time: 69,
    speaker: "Amy",
    text: "Oh. Can you spell the street for me? The street name?",
  },
  { time: 72, speaker: "Owner", text: "L, O, A, D, W, I, C." },
  {
    time: 76,
    speaker: "Amy",
    text: "K. I get it. Waldrick Street. Indeed. Try it. Zip code 48224, correct?",
  },
  { time: 82, speaker: "Owner", text: "That's correct." },
  {
    time: 84,
    speaker: "Amy",
    text: "And do you have a price in mind for this one?",
  },
  { time: 86, speaker: "Owner", text: "No." },
  {
    time: 88,
    speaker: "Amy",
    text: "Okay. Does it need any repairs or any updates?",
  },
  {
    time: 93,
    speaker: "Owner",
    text: "I mean, it's rented, so I'm pretty sure. More than likely, yeah.",
  },
  {
    time: 99,
    speaker: "Amy",
    text: "Okay. Is it rented month to month or annual?",
  },
  { time: 102, speaker: "Owner", text: "Month to month." },
  { time: 105, speaker: "Amy", text: "Okay. And how old is the roof?" },
  {
    time: 110,
    speaker: "Owner",
    text: "I want to think it's about eight years old.",
  },
  { time: 114, speaker: "Amy", text: "And what about the H vac?" },
  { time: 117, speaker: "Owner", text: "It has regular H vac." },
  {
    time: 122,
    speaker: "Amy",
    text: "Okay. And it's two bedrooms, one bathroom and 1,000 square feet, correct?",
  },
  { time: 127, speaker: "Owner", text: "Correct." },
  {
    time: 128,
    speaker: "Amy",
    text: "All right. You said it's rented at the moment, so why are you thinking about selling?",
  },
  { time: 135, speaker: "Owner", text: "Yeah, I would consider." },
  {
    time: 140,
    speaker: "Amy",
    text: "Yeah, I was asking why are you considering selling this one, seeing that it's rented at the moment?",
  },
  { time: 145, speaker: "Owner", text: "Because I live in New York." },
  {
    time: 147,
    speaker: "Amy",
    text: "Oh. Yeah, that's why. Okay. And if we came to an agreement, how much time would you need to close?",
  },
  {
    time: 156,
    speaker: "Owner",
    text: "I don't think I would need a whole lot of time.",
  },
  { time: 159, speaker: "Amy", text: "So we can do it as soon as possible?" },
  { time: 162, speaker: "Owner", text: "Yeah." },
  {
    time: 163,
    speaker: "Amy",
    text: "All right. And the properties off market, correct?",
  },
  { time: 166, speaker: "Owner", text: "It's off market. Yes, it is." },
  {
    time: 168,
    speaker: "Amy",
    text: "Okay, let me just confirm with you. The name is Ian Chapman and the address is the one at 4890 Lawdwick's. P&D for it. The code, 48224. Do you have an email that I can contact you on?",
  },
  { time: 179, speaker: "Owner", text: "Not right now." },
  {
    time: 181,
    speaker: "Amy",
    text: "All right, got it. While I got all the info from you here, we're going to run the numbers and give you a call back. Thank you so much for your time.",
  },
  { time: 187, speaker: "Owner", text: "Have a good one. Bye. Bye." },
];
export const transcript2 = [
  { time: 1, speaker: "Jane", text: "Hello?" },
  { time: 2, speaker: "Owner", text: "Yes." },
  {
    time: 3,
    speaker: "Jane",
    text: "Yeah, this is the phone number for Bernard.",
  },
  { time: 6, speaker: "Owner", text: "Who is it?" },
  {
    time: 7,
    speaker: "Jane",
    text: "This is Jane, actually is calling about the property on Ocean Avenue in Florida. Yeah, I was just checking if you might consider selling this one. Maybe now or anytime soon.",
  },
  { time: 18, speaker: "Owner", text: "Yeah, it's for sale." },
  { time: 21, speaker: "Jane", text: "Is it listed right now?" },
  { time: 24, speaker: "Owner", text: "No." },
  {
    time: 25,
    speaker: "Jane",
    text: "Okay, and how much you're asking for? Like, for the price? Okay. And two bedrooms and one bathroom.",
  },
  { time: 34, speaker: "Owner", text: "Yeah." },
  {
    time: 34,
    speaker: "Jane",
    text: "Right. Okay. Does he need, like any kind of repairs, do you think? Major, minor ones. Have you made any updates?",
  },
  {
    time: 42,
    speaker: "Owner",
    text: "No, doesn't need any repairs. It has new windows, new electric. It's kind of outdated. You know, the kitchen and bathroom are kind of outdated, but nothing needs. Everything's good.",
  },
  {
    time: 58,
    speaker: "Jane",
    text: "Okay, great. And currently like vacant or you're still living there?",
  },
  { time: 64, speaker: "Owner", text: "It's tenant in there right now." },
  {
    time: 67,
    speaker: "Jane",
    text: "Oh, okay. So may I ask what makes you want to sell the property?",
  },
  {
    time: 71,
    speaker: "Owner",
    text: "Too hot down there. Too hot in Florida for me. I'm a Pennsylvania boy.",
  },
  {
    time: 77,
    speaker: "Jane",
    text: "Okay, I got you. And the one on 811 Ocean Ave. In Florida with a zip code, 32169. And speaking with the owner, Berner.",
  },
  { time: 86, speaker: "Owner", text: "Yeah." },
  {
    time: 86,
    speaker: "Jane",
    text: "Right. Okay. And how soon do you think we can close on the property? If we came to an agreement and everything goes your way, 60 days. Okay, sure. Okay. We will get back with you as soon as possible. Do you have an email? No, it's okay. We'll get back with you on the same phone number. Thank you so much. Have a good one.",
  },
];
export const transcript3 = [
  {
    time: 1,
    speaker: "Leah",
    text: "Hello. Hi, this is Leah with Prime Homebuys. How are you doing? Good to hear that. I was interested in the house at Go. Chris Sands Drive. I thought to ask you if you may be planning to film the near future.",
  },
  { time: 19, speaker: "Owner", text: "Yes, I want 127,000 for 127." },
  {
    time: 24,
    speaker: "Leah",
    text: "Okay. So as far as I know, the house is in good condition. Nearly two bedroom bathroom and 1,000 square feet, correct?",
  },
  { time: 36, speaker: "Owner", text: "Yes." },
  {
    time: 37,
    speaker: "Leah",
    text: "That's great. So does it have any car garages? Because honestly, I don't know how much. Hello?",
  },
  { time: 52, speaker: "Owner", text: "Yes." },
  {
    time: 54,
    speaker: "Leah",
    text: "Okay, so how many car garages does it have?",
  },
  { time: 58, speaker: "Owner", text: "Single car?" },
  {
    time: 59,
    speaker: "Leah",
    text: "Okay, so maybe asking you, it looks in a good condition from the outside. From the inside, does it need any kind of like major minor repairs?",
  },
  {
    time: 68,
    speaker: "Owner",
    text: "Like the bathroom has new metal roof, has new vinyl siding, plus it has a new sunroom on the back.",
  },
  { time: 79, speaker: "Leah", text: "Okay." },
  { time: 81, speaker: "Owner", text: "Roughly 20 by 16." },
  {
    time: 85,
    speaker: "Leah",
    text: "Okay, so what about the bathrooms? Have they been updated recently or.",
  },
  { time: 90, speaker: "Owner", text: "Yes." },
  {
    time: 94,
    speaker: "Leah",
    text: "That's good. So if we can get an agreement, how much time will we need for the closing? Can we do it within 30 days? That's great. Okay. Okay, so maybe asking you why have you like thought about the idea of selling at some point, as I'm assuming it's your primary residence.",
  },
  { time: 113, speaker: "Owner", text: "No, it's not. It's a rental." },
  {
    time: 115,
    speaker: "Leah",
    text: "Okay, so why have you like thought about selling at some point? I'm sorry, why have you thought about selling at some point?",
  },
  {
    time: 126,
    speaker: "Owner",
    text: "I'm just ready to get rid of it. I don't need it. I'm tired of renting.",
  },
  {
    time: 130,
    speaker: "Leah",
    text: "Got your point. Okay, and is it free and clear or you still like say something on it?",
  },
  { time: 136, speaker: "Owner", text: "No, it's free and clear." },
  {
    time: 138,
    speaker: "Leah",
    text: "That's great. Okay, so I know it was built in 1989. So has you been like owning the house since then or how many years have you owned the house?",
  },
  { time: 149, speaker: "Owner", text: "Yeah." },
  {
    time: 149,
    speaker: "Leah",
    text: "Oh, that's great. Okay, great. So I just want to confirm the address one more time with you. Is 5428. Go. Chris Sands Drive, Mills, North Carolina 28348. And your last name is? Mr. Dean. Can I have your.",
  },
  { time: 167, speaker: "Owner", text: "Green Hill." },
  {
    time: 170,
    speaker: "Leah",
    text: "I'm sorry, you're. You cut it off. Can you repeat again?",
  },
  {
    time: 172,
    speaker: "Owner",
    text: "I'm sorry, My last name is Green Hill.",
  },
  {
    time: 176,
    speaker: "Leah",
    text: "Green Hill. Okay, so your first name is Billy Belly. Okay, that's great, Mr. Belly. So I'm gonna just go back and. For my partner with your asking price and everything and get back to you as soon as possible on the same number tomorrow morning. Is that okay?",
  },
  { time: 193, speaker: "Owner", text: "That's fine." },
  {
    time: 194,
    speaker: "Leah",
    text: "That's great. Thank you so much. I appreciate it. Have a good day.",
  },
];
export const transcript4 = [
  { time: 1, speaker: "Owner", text: "Hello?" },
  {
    time: 2,
    speaker: "Mark",
    text: "Hello, good morning, this is Mark Anderson speaking. I'm looking to get a hold of Ms. Costa.",
  },
  {
    time: 8,
    speaker: "Owner",
    text: "Where are you calling from please?",
  },
  {
    time: 10,
    speaker: "Mark",
    text: "I'm calling from homebuyers Inc. About the property at Dartmouth Avenue. I'm sorry? Drive. We were just looking to see if you're interested in selling the property. The near future.",
  },
  {
    time: 21,
    speaker: "Owner",
    text: "I am probably going to sell it in the next three to six months.",
  },
  {
    time: 25,
    speaker: "Mark",
    text: "Yes, you said three to six months.",
  },
  { time: 28, speaker: "Owner", text: "Maybe sooner." },
  {
    time: 30,
    speaker: "Mark",
    text: "Okay. And you have two bedrooms and two bathrooms on the property, right?",
  },
  { time: 34, speaker: "Owner", text: "Yes." },
  {
    time: 36,
    speaker: "Mark",
    text: "Okay. And how old is the roof and the air conditioning?",
  },
  {
    time: 41,
    speaker: "Owner",
    text: "The air conditioning is under a year. The roof is an older tiled roof. But I've had a five point mitigation done in the last year. There's no broken tiles.",
  },
  {
    time: 57,
    speaker: "Mark",
    text: "Okay. Any major or minor repairs that we need to do on the property in case you want from you?",
  },
  {
    time: 62,
    speaker: "Owner",
    text: "No, I had a new electrical box put in. I had the electrical box upgraded. I had new air conditioning put in. I have new LVP flooring put in. No, no, there's no major repairs on the house.",
  },
  {
    time: 78,
    speaker: "Mark",
    text: "Okay. And generally speaking, how much do you want for the property?",
  },
  {
    time: 84,
    speaker: "Owner",
    text: "It's been estimated at about 600. I have a double lot in the pool.",
  },
  {
    time: 92,
    speaker: "Mark",
    text: "Oh, coming with the property? Yeah.",
  },
  { time: 95, speaker: "Owner", text: "Excuse me." },
  {
    time: 97,
    speaker: "Mark",
    text: "You're selling them along with the property? Yeah, they're coming together?",
  },
  {
    time: 101,
    speaker: "Owner",
    text: "Yes, yes. It's a whole thing. It's a fenced in yard. It's a double lot. Yeah. Mm.",
  },
  {
    time: 107,
    speaker: "Mark",
    text: "Okay. And you said in how many weeks or months are you looking to do a closing for the property?",
  },
  { time: 113, speaker: "Owner", text: "Probably three months." },
  {
    time: 116,
    speaker: "Mark",
    text: "Three months. Okay. And you have an email that we can use.",
  },
  { time: 122, speaker: "Owner", text: "S H E a." },
  { time: 123, speaker: "Mark", text: "One second, one more time please." },
  {
    time: 126,
    speaker: "Owner",
    text: "Sh S as in Sam. H as in Harry, E as in Elephant. A as in apple59ol.com.",
  },
  {
    time: 137,
    speaker: "Mark",
    text: "Cheryl, I'm sorry, one more time. You cut off sh s as in.",
  },
  {
    time: 142,
    speaker: "Owner",
    text: "Sam, H as in Harry, E as in Elephant. A as in apple59ol.com thank you so much.",
  },
  {
    time: 151,
    speaker: "Mark",
    text: "And when is a good time that we can call you back with an offer? Tomorrow.",
  },
  { time: 156, speaker: "Owner", text: "Probably in the afternoon." },
  {
    time: 157,
    speaker: "Mark",
    text: "Okay, let me confirm the address. It's 205 Darknow Drive, Lake Worth, Florida 33460. And I have the pleasure of speaking to Cheryl Costa.",
  },
  {
    time: 169,
    speaker: "Owner",
    text: "Yes, it's in the College park section, which is the higher end section of Lake Worth.",
  },
  {
    time: 174,
    speaker: "Mark",
    text: "And may I know what is your bottom line in terms of price?",
  },
  {
    time: 178,
    speaker: "Owner",
    text: "I'm not going anything under 600. I know the house is worth more.",
  },
  { time: 182, speaker: "Mark", text: "Than that, but that's." },
  { time: 184, speaker: "Owner", text: "Yes." },
  {
    time: 185,
    speaker: "Mark",
    text: "Okay, last question before I go. You said why would you consider selling the property?",
  },
  {
    time: 190,
    speaker: "Owner",
    text: "Why am I considered selling the property? My son just had a baby, so I'm buying a smaller condo on the beach and one up in New York.",
  },
  {
    time: 199,
    speaker: "Mark",
    text: "All right, thank you so much for the information. We got to do the math and call you back tomorrow with an offer. This is Mark Anderson speaking to you.",
  },
  { time: 206, speaker: "Owner", text: "Thank you." },
  {
    time: 207,
    speaker: "Mark",
    text: "Have a great rest of your day. Thank you.",
  },
  { time: 209, speaker: "Owner", text: "You, too." },
  { time: 210, speaker: "Mark", text: "Bye. Bye." },
];
export const transcript5 = [
  {
    time: 3,
    speaker: "Rose",
    text: "Hello? Yes, hi, this is Rose. I'm speaking with Mr. Tillman.",
  },
  { time: 10, speaker: "Owner", text: "Yes, you are." },
  {
    time: 11,
    speaker: "Rose",
    text: "I'm calling in regard the property on 25936 Southwest 122nd Place. I'm talking to the owner. Right?",
  },
  { time: 21, speaker: "Owner", text: "Yes, you are." },
  {
    time: 22,
    speaker: "Rose",
    text: "Okay. I'm reaching out to check if you're interested in selling the property anytime soon. Are you thinking about it?",
  },
  {
    time: 30,
    speaker: "Owner",
    text: "I'm considering it. That's a. That's a good. Yes, I'm considering it.",
  },
  {
    time: 35,
    speaker: "Rose",
    text: "Okay, so I believe it's not listed on the market right now. Is it correct?",
  },
  { time: 41, speaker: "Owner", text: "No." },
  {
    time: 42,
    speaker: "Rose",
    text: "Okay, so I think it has three bedrooms and two full bathrooms. Is it correct?",
  },
  { time: 49, speaker: "Owner", text: "Say it again." },
  {
    time: 51,
    speaker: "Rose",
    text: "I think it has three bedrooms and two full bathrooms. Is it correct?",
  },
  { time: 55, speaker: "Owner", text: "Yes. Yes." },
  {
    time: 56,
    speaker: "Rose",
    text: "Okay, so for now, do you have an asking price or number, Mike?",
  },
  {
    time: 63,
    speaker: "Owner",
    text: "Not really, other than I kind of been looking at the market. So I have an idea in mind, but. Okay.",
  },
  {
    time: 71,
    speaker: "Rose",
    text: "Okay, that's totally fine. But did you made any kind of upgrades within the last five years.",
  },
  {
    time: 79,
    speaker: "Owner",
    text: "Other than updating my kids bathroom? I've updated the kitchen, but outside of that it's pretty. It's pretty standard still.",
  },
  {
    time: 89,
    speaker: "Rose",
    text: "Okay, perfect. So that means there is no major or minor repairs that need to be done, right?",
  },
  {
    time: 96,
    speaker: "Owner",
    text: "No, nothing. Nothing. I mean if you're saying no major or minor, there's some little stuff here or there, but. But no like major issues.",
  },
  {
    time: 106,
    speaker: "Rose",
    text: "Oh, I got it. Okay, perfect. So if you get a good offer, can you sell the property as soon as possible?",
  },
  {
    time: 114,
    speaker: "Owner",
    text: "Say it again? I'm sorry. If you get talking, you slow down. Please slow down. Because you are running so fast. I'm trying to grab.",
  },
  { time: 123, speaker: "Rose", text: "Oh, okay." },
  {
    time: 126,
    speaker: "Owner",
    text: "Because you're running at 100 miles an hour.",
  },
  {
    time: 128,
    speaker: "Rose",
    text: "Okay, I'm sorry about that. I was just asking you, if you get a good offer, can you sell the property as soon as possible?",
  },
  { time: 137, speaker: "Owner", text: "What does that mean?" },
  {
    time: 139,
    speaker: "Rose",
    text: "If you get a good offer that you accepted, you will be able to sell the property as soon as possible. Or you need some time to close. I mean like two, three months maybe. Or you can sell within 30 days.",
  },
  {
    time: 152,
    speaker: "Owner",
    text: "You know, I would. I would need a little bit of time to kind of get myself situated and know what, I'm where I'm going. So. No, it would not be like, oh, okay, I want to sell today and then I'm out next week. No, that is. That is not gonna happen.",
  },
  {
    time: 166,
    speaker: "Rose",
    text: "Okay, so can we say three months will be good for you?",
  },
  {
    time: 172,
    speaker: "Owner",
    text: "Yeah, you know, depending on what we. Where we had and what I'm doing as well.",
  },
  {
    time: 177,
    speaker: "Rose",
    text: "Okay, I got it. But can you please tell me why you consider selling the property.",
  },
  {
    time: 185,
    speaker: "Owner",
    text: "I'm at the beginning stages of the divorce and at where we move it.",
  },
  {
    time: 190,
    speaker: "Rose",
    text: "Oh, I got it. I understand. Okay, so just let me confirm the address again is 25936 Southwest 122nd Place, Homestead, Florida, code 33032. Is it correct?",
  },
  { time: 205, speaker: "Owner", text: "Correct." },
  {
    time: 206,
    speaker: "Rose",
    text: "Okay, and your Last name is Mr. Tailman, right?",
  },
  { time: 210, speaker: "Owner", text: "Yes." },
  {
    time: 211,
    speaker: "Rose",
    text: "Okay, and what is your first name?",
  },
  { time: 214, speaker: "Owner", text: "Lolly." },
  {
    time: 215,
    speaker: "Rose",
    text: "Okay. And the best phone number? Treat you on in the number I'm calling you right now.",
  },
  { time: 221, speaker: "Owner", text: "Correct." },
  {
    time: 222,
    speaker: "Rose",
    text: "Okay, so my manager will call you back within 24 hours. Thank you so much for your time. Have a good one.",
  },
  { time: 228, speaker: "Owner", text: "All right, thank you." },
  { time: 230, speaker: "Rose", text: "Bye. Bye." },
];
